/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sudokuboardgen1 */

#ifndef _Included_sudokuboardgen1
#define _Included_sudokuboardgen1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sudokuboardgen1
 * Method:    boardgen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sudokuboardgen1_boardgen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
